# Main menu
[[main]]
  name = "Despre"
  url = "/about/"
  weight = 1

[[main]]
  name = "Proiecte"
  url = "/projects/"
  weight = 2

[[main]]
  name = "Echipa"
  url = "/team/"
  weight = 3

[[main]]
  name = "Implică-te"
  url = "/get-involved/"
  weight = 4

[[main]]
  name = "Noutăți"
  url = "/news/"
  weight = 5

[[main]]
  name = "Donează"
  url = "/donate/"
  weight = 6

# Footer menu
[[footer]]
  name = "Contact"
  url = "/contact/"
  weight = 1

[[footer]]
  name = "Impressum"
  url = "/impressum/"
  weight = 2

[[footer]]
  name = "Politica de confidențialitate"
  url = "/datenschutz/"
  weight = 3

[[footer]]
  name = "Statut"
  url = "/satzung/"
  weight = 4
